### ISSUE TITLE
Can't select data items from large schema; cannot use schema that uses $ref

### ISSUE THREAD

**Issue by Altreus** [Humanstate/json-schema-tojson#7]
I can't see a way to get this module to produce *some* data from a bigger schema. Consider the pet store example:

https://app.swaggerhub.com/apis/helen/petstore/2.0

There appears to be no way to produce a generator that absorbs this entire schema and then spits out specifically an Order, or User, or Pet.

This produces the secondary issue that one cannot use any data object that uses a `$ref`. In order to construct data from a larger schema, it is necessary to follow the ref manually. Where one might prefer to use

```perl
$generator->json_schema_to_json(schema => 
    $swaggerdoc->{paths}{'/pet/findByStatus'}{get}{responses}{200}{schema}
);
```

```yaml
  /pet/findByStatus:
    get:
...
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
```

Instead it is necessary to dereference `#/definitions/Pet` and then perform the "array" part yourself.

```perl
map {
    $generator->json_schema_to_json(schema => 
        $swaggerdoc->{definitions}{Pet}
    )
} 0..rand(10);
```

But even *this* doesn't work if the definition for `Pet` contains a ref... which it does

```yaml
  Pet:
    ...
    properties:
      ...
      category:
        $ref: '#/definitions/Category'
```

There appears to be no way to generate this data without expanding the refs in the document.

**Comment by leejo** [comment]
This might be a regresssion - the underlying module i use to parse the JSON Schema document changes frequently enough that most of the time any breakage is because of it. I'll add a test case and fix when I get time.

**Comment by Altreus** [comment]
I can pass it a full schema but I can't select which data type to generate. It seems I can only pass a schema that defines a single data type.

**Comment by Altreus** [comment]
To clarify, it seems to be OK if the schema uses `$ref`; the problem is simply that in order to do that, I have to provide a complex schema, from which I cannot then select an individual data type to generate stuff from.

It allows me to pass the entire pet store schema, but I cannot then use the generator to create a single `Pet`

**Comment by leejo** [comment]
A ha, I see.

In that case - patches welcome :)

Ta,
Lee.

Lee A Johnson
https://leejo.github.io

**Comment by Altreus** [comment]
After experimentation with help from IRC I have learned that you can use JSON::Validator in conjuction with this module to get what I needed:

```
my $jv = $jv->new;
$jv->schema('petstore.json');

my $generator = JSON::Schema::ToJSON->new;

my $response = $generator->json_schema_to_json(schema => $jv->get('/definitions/Pet'));
```

I think I can find time to add this to the docs :)
